server:
  port: 8080

spring:
  resources:
    static-locations: "classpath:/static/"
#  security:
#    oauth2:
#      client:
#        provider:
#          okta:
#            issuerUri: https://dev-589473.okta.com/oauth2/default
#

okta:
  oauth2:
    issuer: https://dev-589473.okta.com/oauth2/default
    clientId: 0oao19viwPfHGqug0356
    clientSecret: QDX2JA5_vvMbAmfONLnGQVwPbr6uqemOXX_RPizM
    redirectUri: /implicit/callback
    scopes: openid,email,profile


logging:
  level:
    root: DEBUG